"""Adds or Drops Created Date to Users Table

Revision ID: 38c7cbd530bb
Revises: 
Create Date: 2022-06-07 21:49:59.609047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c7cbd530bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db_con = op.get_bind()
    if db_con.engine.has_table('users') and 'created_date' not in [col.get('name') for col in sa.inspect(db_con).get_columns("users")]:
        op.add_column('users', sa.Column('created_date', sa.DateTime()))
        op.execute("UPDATE users SET created_date = date() WHERE created_date is null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
