"""empty message

Revision ID: 4162ed1ab567
Revises: 
Create Date: 2022-06-27 21:20:42.215540

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4162ed1ab567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'structureMarkets',
        sa.Column('struc_id',
                  sa.BigInteger(),
                  autoincrement=False,
                  nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('typeID', sa.BigInteger(), nullable=False),
        sa.Column('solarSystemID', sa.BigInteger(), nullable=False),
        sa.Column('sell_orders', sa.PickleType(), nullable=True),
        sa.Column('history', sa.PickleType(), nullable=True),
        sa.ForeignKeyConstraint(
            ['solarSystemID'],
            ['solarSystems.solarSystemID'],
        ), sa.ForeignKeyConstraint(
            ['typeID'],
            ['invTypes.typeID'],
        ), sa.PrimaryKeyConstraint('struc_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structureMarkets')
    # ### end Alembic commands ###
