"""empty message

Revision ID: b594bef8ef6c
Revises: beab5bf292c8
Create Date: 2022-07-01 16:43:03.355154

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b594bef8ef6c'
down_revision = 'beab5bf292c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structureMarkets',
                  sa.Column('sell_orders_expiry', sa.DateTime(), nullable=True))
    op.add_column('structureMarkets',
                  sa.Column('history_expiry', sa.DateTime(), nullable=True))
    op.drop_column('structureMarkets', 'esi_expiry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'structureMarkets',
        sa.Column('esi_expiry', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('structureMarkets', 'history_expiry')
    op.drop_column('structureMarkets', 'sell_orders_expiry')
    # ### end Alembic commands ###
