"""empty message

Revision ID: bf3af2d67e85
Revises: 
Create Date: 2022-06-30 20:41:13.196613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3af2d67e85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structureMarkets',
    sa.Column('struc_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('typeID', sa.BigInteger(), nullable=True),
    sa.Column('solarSystemID', sa.BigInteger(), nullable=True),
    sa.Column('sell_orders', sa.PickleType(), nullable=True),
    sa.Column('history', sa.PickleType(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solarSystemID'], ['solarSystems.solarSystemID'], ),
    sa.ForeignKeyConstraint(['typeID'], ['invTypes.typeID'], ),
    sa.PrimaryKeyConstraint('struc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structureMarkets')
    # ### end Alembic commands ###
